name: flutter_tiktok
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 加载动画库
  flutter_spinkit: ^4.1.2
  # Bilibili开源的视频播放组件
  fijkplayer: ^0.8.3
  # 基础的点击
  tapped: any
  # map取值
  safemap: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # 下拉刷新上拉加载
  pull_to_refresh: ^2.0.0

  #toast
  fluttertoast: ^3.1.3

  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3

  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.3

  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  fluintl: ^0.1.2

  # https://github.com/flutterchina/dio
  dio: ^3.0.7

  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.21.0

  # https://github.com/renefloor/flutter_cached_network_image
  #  cached_network_image: ^1.1.3
  cached_network_image: ^2.0.0-rc

  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.0.2

  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2

  # https://github.com/flutterchina/flukit.
  flukit: ^1.0.0

  #状态管理
  provider: ^3.0.0+1


  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1

  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.1.1

  #https://github.com/marcojakob/dart-event-bus
  event_bus: ^1.1.0

  #获取应用包的信息 https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^0.4.0+2

  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^ 0.3.18+1

  #https://github.com/leisim/logger.git  日志工具
  logger: ^0.6.0

  #打开相册
  image_picker: ^0.6.1+4

  #持久化存储
  shared_preferences: ^2.0.13

  #七牛云
  qiniu_flutter_sdk: ^0.2.0

  #FFmpeg
  flutter_ffmpeg: ^0.4.2

  #数据库
  sqflite: ^1.3.1

  #Dart路径操作库
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
